# Generated by Django 2.2 on 2020-10-15 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultycode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='faculty')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('facultycoverimg', models.ImageField(upload_to='faculty')),
                ('img', models.ImageField(upload_to='faculty')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentcode', models.CharField(max_length=100)),
                ('subjectcode', models.CharField(max_length=100)),
                ('subjectname', models.CharField(max_length=100)),
                ('starttime', models.CharField(choices=[('9:00 AM', '9:00 AM'), ('10:00 AM', '10:00 AM'), ('11:00 AM', '11:00 AM'), ('12:00 PM', '12:00 PM'), ('1:00 PM', '1:00 PM')], max_length=10)),
                ('stoptime', models.CharField(choices=[('9:00 AM', '9:00 AM'), ('10:00 AM', '10:00 AM'), ('11:00 AM', '11:00 AM'), ('12:00 PM', '12:00 PM'), ('1:00 PM', '1:00 PM')], max_length=10)),
                ('meetlink', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('docs', models.FileField(upload_to='docs')),
                ('slug', models.SlugField()),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Faculty'),
        ),
    ]
