# Generated by Django 2.2 on 2020-09-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='faculty')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='link',
        ),
        migrations.AddField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
