# Generated by Django 2.2 on 2020-09-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200930_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Faculty'),
        ),
    ]
