# Generated by Django 2.2 on 2020-09-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='faculty_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
